name: DutchyBack
main: nl.thedutchmc.dutchyback.Back
version: 1.0.1
api-version: 1.16
author: TheDutchMC
description: A plugin which adds /back
softdepend: [DutchyTPA, DutchyHome]
commands:
 back:
  description: Go to your previous location